development:
  news_api_key: Rails.application.secrets.news_api_key
  enhance_image_tag: true
  static_image_support: false
production:
  news_api_key: Rails.application.secrets.news_api_key
  enhance_image_tag: true
  static_image_support: true
test:
  news_api_key: Rails.application.secrets.news_api_key
  enhance_image_tag: true
  static_image_support: false
